using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using UnityEditor;
using UnityEngine;

namespace Editor.CMSEditor.CodeGenerators
{
    namespace Common
    {
        public static class CmsModelsGenerator
        {
            private const string ResourcesRoot = "Assets/Resources";
            private const string CmsModelsRoot = "Assets/Resources/CMS";
            private const string OutputDir = "Assets/GeneratedCodeBase";
            private const string OutputFileName = "Constants.Models.cs";

            [MenuItem("CMS/Generate Models Constants")]
            public static void Generate()
            {
                if (!AssetDatabase.IsValidFolder(ResourcesRoot))
                {
                    Debug.LogError($"Resources folder not found: {ResourcesRoot}");
                    return;
                }

                if (!AssetDatabase.IsValidFolder(CmsModelsRoot))
                {
                    Debug.LogError($"CMS Models folder not found: {CmsModelsRoot}");
                    return;
                }

                var guids = AssetDatabase.FindAssets("t:prefab", new[] {CmsModelsRoot});
                var items = new List<Item>(guids.Length);

                foreach (var guid in guids)
                {
                    var assetPath =
                        AssetDatabase.GUIDToAssetPath(guid);
                    if (!assetPath.EndsWith(".prefab", StringComparison.OrdinalIgnoreCase))
                        continue;

                    var resourcesRel = ToResourcesRelative(assetPath);
                    var fileName = Path.GetFileName(resourcesRel);
                    var folderRel = Path.GetDirectoryName(resourcesRel)
                        ?.Replace("\\", "/") ?? string.Empty;

                    var category = GetCategory(folderRel);
                    var constName = ToIdentifier(fileName);

                    items.Add(new Item
                    {
                        Category = category,
                        ConstName = constName,
                        ResourcesPath = resourcesRel
                    });
                }

                var nameBuckets = new Dictionary<string, int>(StringComparer.Ordinal);
                foreach (var it in items)
                {
                    if (!nameBuckets.TryGetValue(it.ConstName, out var n))
                    {
                        nameBuckets[it.ConstName] = 1;
                    }
                    else
                    {
                        n++;
                        nameBuckets[it.ConstName] = n;
                        it.ConstName += $"_{n}";
                    }
                }

                var groups = items
                    .GroupBy(i => i.Category)
                    .OrderBy(g => g.Key, StringComparer.OrdinalIgnoreCase)
                    .ToList();

                if (!Directory.Exists(OutputDir))
                    Directory.CreateDirectory(OutputDir);

                var sb = new StringBuilder(16 * 1024);
                sb.AppendLine(
                    "// <auto-generated>  This file is generated by CmsModelsGenerator. Do not edit manually. </auto-generated>");
                sb.AppendLine("namespace Constants");
                sb.AppendLine("{");
                sb.AppendLine("    public static class Models");
                sb.AppendLine("    {");


                foreach (var g in groups)
                {
                    sb.AppendLine();
                    sb.AppendLine($"        // --- {g.Key} ---");
                    foreach (var it in g.OrderBy(i => i.ConstName, StringComparer.OrdinalIgnoreCase))
                    {
                        sb.AppendLine($"        public const string {it.ConstName} = \"{it.ResourcesPath}\";");
                    }
                }

                sb.AppendLine("    }");
                sb.AppendLine("}");

                var outPath = Path.Combine(OutputDir, OutputFileName).Replace("\\", "/");
                File.WriteAllText(outPath, sb.ToString(), new UTF8Encoding(encoderShouldEmitUTF8Identifier: false));
                AssetDatabase.Refresh();

                Debug.Log($"[CMS] Generated {items.Count} model paths → {outPath}");
            }


            private static string ToResourcesRelative(string assetPath)
            {
                var rel = assetPath.Substring(ResourcesRoot.Length + 1);
                if (rel.EndsWith(".prefab", StringComparison.OrdinalIgnoreCase))
                    rel = rel.Substring(0, rel.Length - ".prefab".Length);
                return rel.Replace("\\", "/");
            }

            private static string GetCategory(string folderRel)
            {
                const string head = "CMS/Models/";
                var idx = folderRel.IndexOf(head, StringComparison.Ordinal);
                if (idx < 0) return "Ungrouped";
                var tail = folderRel.Substring(idx + head.Length);
                var firstSlash = tail.IndexOf('/');
                var cat = firstSlash >= 0 ? tail.Substring(0, firstSlash) : tail;
                return string.IsNullOrEmpty(cat) ? "Ungrouped" : cat;
            }

            private static string ToIdentifier(string name)
            {
                var parts = Regex.Split(name, @"[^A-Za-z0-9]+")
                    .Where(p => !string.IsNullOrEmpty(p))
                    .ToArray();

                string pascal;
                if (parts.Length == 0)
                {
                    pascal = Regex.Replace(name, @"[^A-Za-z0-9]+", "_");
                }
                else
                {
                    pascal = string.Concat(parts.Select(Capitalize));
                }

                if (char.IsDigit(pascal[0]))
                    pascal = "_" + pascal;

                pascal = Regex.Replace(pascal, @"[^A-Za-z0-9_]", "");

                if (string.IsNullOrEmpty(pascal))
                    pascal = "_Model";

                return pascal;
            }

            private static string Capitalize(string s)
            {
                if (string.IsNullOrEmpty(s)) return s;
                if (s.Length == 1) return char.ToUpperInvariant(s[0]).ToString();
                return char.ToUpperInvariant(s[0]) + s.Substring(1);
            }

            private class Item
            {
                public string Category;
                public string ConstName;
                public string ResourcesPath;
            }
        }
    }
}